### ISSUE TITLE
Could you add Heroicons support?

### ISSUE THREAD

**Issue by iamdagy** [christopherafbjur/sanity-plugin-icon-picker#12]
It would be nice to have them in the options.

**Comment by christopherafbjur** [comment]
Will have a look to see if we decide to implement this separately or in sync with #13 @iamdagy

**Comment by christopherafbjur** [comment]
This have now been resolved in [v2.0.0](https://github.com/christopherafbjur/sanity-plugin-icon-picker/releases/tag/v2.0.0). Closing
