### ISSUE TITLE
Use react-icons as a source

### ISSUE THREAD

**Issue by Hahlh** [christopherafbjur/sanity-plugin-icon-picker#13]
[https://github.com/react-icons/react-icons](https://github.com/react-icons/react-icons)

All the goodies are included there, new ones are added and it is constantly updated.

Would resolve #12 and would be awesome in combination with #11 .

**Comment by crankymaracuja** [comment]
This would also resolve #14 💜

**Comment by christopherafbjur** [comment]
Will have a look into this asap!

**Comment by christopherafbjur** [comment]
This have now been resolved in [v2.0.0](https://github.com/christopherafbjur/sanity-plugin-icon-picker/releases/tag/v2.0.0). Closing
