### ISSUE TITLE
Add FontAwesome Brands Icons

### ISSUE THREAD

**Issue by crankymaracuja** [christopherafbjur/sanity-plugin-icon-picker#14]
I would love to also use the FontAwesome Brands Icons (fab).

Can I contribute?

**Comment by crankymaracuja** [comment]
I just added a pull request 😊

**Comment by christopherafbjur** [comment]
This have now been resolved in [v2.0.0](https://github.com/christopherafbjur/sanity-plugin-icon-picker/releases/tag/v2.0.0). Closing
