### ISSUE TITLE
Use of decamelize 5 breaks the studio in Safari

### ISSUE THREAD

**Issue by geoffreyjball** [christopherafbjur/sanity-plugin-icon-picker#21]
The implementation of decamelize v5 in [this commit](https://github.com/christopherafbjur/sanity-plugin-icon-picker/commit/87dcc33b0c48068e370ffc3f3b9b656ae9e650e9) breaks the studio in Safari, which cannot handle Regex lookbehinds. A blank page appears with only the error `Invalid regular expression: invalid group specifier name` in the dev console. The maintainer of decamelize [recommends staying on v3](https://github.com/sindresorhus/decamelize/commit/da8552d335f9067354ca9b93378482eb9f1fb821) of the plugin until Safari [supports lookbehinds](https://caniuse.com/?search=lookbehind).

**Comment by christopherafbjur** [comment]
Thank you @geoffreyjball, very well written issue 👍. Will look into this ASAP
