### ISSUE TITLE
Icons are a bit cut of

### ISSUE THREAD

**Issue by tobiaswild** [christopherafbjur/sanity-plugin-icon-picker#24]
I noticed that the Icons are always a bit cut off (see 1 and 2). 
I don't know how to fix this, but this only applies to icons that use this return (3) instead of this (4).
Because these look normal (5).

1. ![image](https://user-images.githubusercontent.com/46871747/181387102-70b608cb-22c5-4221-9293-4a916af41153.png)
2. ![image](https://user-images.githubusercontent.com/46871747/181387250-a8a4866c-a263-4a1c-84a0-c254641191e1.png)
3. ![image](https://user-images.githubusercontent.com/46871747/181388076-1d9e0c08-1151-489e-8ad5-abe6244cf1c8.png)
4. ![image](https://user-images.githubusercontent.com/46871747/181388218-d0ddde81-61ea-4dbf-bb99-e123a6a78377.png)
5. ![image](https://user-images.githubusercontent.com/46871747/181387949-eba8ad75-3d02-4155-ab78-83b92ed0f501.png)

**Comment by chandlervdw** [comment]
+1

**Comment by JohnGemstone** [comment]
Any fixes for this? Makes the plugin unusable for editors.

**Comment by christopherafbjur** [comment]
Thank you for reporting this and sorry for the delay. I will start looking into fixing these recent issues asap!
