### ISSUE TITLE
Sanity V3 Upgrade?

### ISSUE THREAD

**Issue by dumle11** [christopherafbjur/sanity-plugin-icon-picker#26]
Hello, are there any plans to upgrade this plugin to work with Sanity v3? Thanks!

**Comment by christopherafbjur** [comment]
Definitely, yes! Will try to create a fix for this asap @dumle11 @kevinorin

**Comment by dumle11** [comment]
Awesome, thank you!

**Comment by zacanger** [comment]
@christopherafbjur Kevin has a tentative version on [his fork](https://github.com/kevinorin/sanity-plugin-icon-picker), just testing it out and trying to resolve any outstanding bugs; if you're already working on an upgrade the diff there might be useful. One notable change is that `setIfMissing` seems to be private in v3, we weren't sure what to do about that.

**Comment by kevinorin** [comment]
> Definitely, yes! Will try to create a fix for this asap @dumle11 @kevinorin

Thanks @zacanger , looking forward to v3 update...let me know if you need anything @christopherafbjur

**Comment by christopherafbjur** [comment]
Just finished the V3 version. Please check it out and let me know if you find any bugs

**Comment by hanshenrik** [comment]
Hi! I'm getting this error after upgrading to Sanity Studio v3 and installing `yarn add sanity-plugin-icon-picker@2.1.0`

```
▶ yarn dev
yarn run v1.22.19
$ sanity dev
✔ Checking configuration files...
Sanity Studio using vite@4.1.4 ready in 23916ms and running at http://localhost:3333/
✘ [ERROR] Could not resolve "part:@sanity/form-builder/patch-event"

    ../node_modules/sanity-plugin-icon-picker/dist/index.js:16:26:
      16 │ var _patchEvent = require("part:@sanity/form-builder/patch-event");
         ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "part:@sanity/form-builder/patch-event" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "part:@sanity/components/formfields/default"

    ../node_modules/sanity-plugin-icon-picker/dist/index.js:18:47:
      18 │ var _default2 = _interopRequireDefault(require("part:@sanity/components/formfields/default"));
         ╵                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "part:@sanity/components/formfields/default" as external to exclude it from
  the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

12:10:13 PM [vite] error while updating dependencies:
Error: Build failed with 2 errors:
../node_modules/sanity-plugin-icon-picker/dist/index.js:16:26: ERROR: Could not resolve "part:@sanity/form-builder/patch-event"
../node_modules/sanity-plugin-icon-picker/dist/index.js:18:47: ERROR: Could not resolve "part:@sanity/components/formfields/default"
    at failureErrorWithLog (/Users/hanshenrik/kode/folq/public-pages/node_modules/esbuild/lib/main.js:1604:15)
    at /Users/hanshenrik/kode/folq/public-pages/node_modules/esbuild/lib/main.js:1056:28
    at runOnEndCallbacks (/Users/hanshenrik/kode/folq/public-pages/node_modules/esbuild/lib/main.js:1476:61)
    at buildResponseToResult (/Users/hanshenrik/kode/folq/public-pages/node_modules/esbuild/lib/main.js:1054:7)
    at /Users/hanshenrik/kode/folq/public-pages/node_modules/esbuild/lib/main.js:1166:14
    at responseCallbacks.<computed> (/Users/hanshenrik/kode/folq/public-pages/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/Users/hanshenrik/kode/folq/public-pages/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/Users/hanshenrik/kode/folq/public-pages/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

I'm guessing the imports in this plugins needs to change from `part:` to something else, as mentioned in [this section](https://www.sanity.io/docs/migrating-from-v2#c171df4dd957)?

**Comment by christopherafbjur** [comment]
@hanshenrik Glad it worked out for you! To me the install example in the plugin documentation looks complete, can you please elaborate? Thanks in advance!

**Comment by hanshenrik** [comment]
Ah, sorry again 🤦 My quick glance at the install instructions, since I use `yarn` in the project in question, made me think v2.1.0 was the correct version. Didn't see the `V2 INSTALL COMMAND (DEPRECATED)` title. Sort of weird that Sanity uses `yarn` as example for the deprecated install instructions and `npm` for the current ones 🤷 

So, everything is ok, sorry for the trouble!

<img width="433" alt="Screenshot 2023-03-10 at 15 02 49" src="https://user-images.githubusercontent.com/3757042/224335905-ba742ab7-932b-4130-ba6e-953ee1918cc7.png">
