### ISSUE TITLE
Add custom provider/lib

### ISSUE THREAD

**Issue by christopherafbjur** [christopherafbjur/sanity-plugin-icon-picker#3]
Could be beneficial for users to be able to inject custom icons via schema options.

Need to decide how we handle this.

**Proposal A**
A **custom** property that takes an object of custom **library/provider** as well as a **render** callback method which will pass the current icon iteration of injected lib as a parameter and expects the method to return a proper icon component/element?

**Proposal B**
Similar to **A** but the user has to format the custom icons to a controlled structure before passing them to the **custom** object.

**Comment by fabien** [comment]
Would love to add https://www.carbondesignsystem.com/guidelines/icons/library/ myself when this feature lands. I have no particular preference whether proposal A or B will be best.

**Comment by brandonmlyon** [comment]
I agree this would be great. I'd love to use Streamline icons with this plugin (but I understand they're a massive library with many licensed & not free options).
