### ISSUE TITLE
Deploying NextJS embedded studio breaks studio

### ISSUE THREAD

**Issue by christopherafbjur** [christopherafbjur/sanity-plugin-icon-picker#33]
![image](https://user-images.githubusercontent.com/13018273/226601553-7fd38e70-6390-4a2c-b63f-e63174cdc674.png)
![image](https://user-images.githubusercontent.com/13018273/226601570-dddf78f3-b217-44cd-b9ae-d6dac8b1b08a.png)

[Reference](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1679388874917589)

**Comment by JohnGemstone** [comment]
Hey @christopherafbjur,
could you try adding `swcMinify: false,` to your next config like so:
```ts
const nextConfig = {
  experimental: {
    appDir: true,
  },
  swcMinify: false,
}

```
