### ISSUE TITLE
Stored SVG is not available in GraphQL

### ISSUE THREAD

**Issue by JJK801** [christopherafbjur/sanity-plugin-icon-picker#49]
hi @christopherafbjur ,

I updated my plugin today to use the new storeSvg feature (thanks again for the work)

But it seems like svg propertie es not available in graphQL types (probably because it requires a field in the schema type).

**Comment by christopherafbjur** [comment]
Hi @JJK801,

Can you please provide me some more context of your issue? Not sure I understand why SVG properties should be available in GraphQL types. Should it not suffice with String type since we store the svg as a string?

**Comment by christopherafbjur** [comment]
Thank you @JJK801! Yes you are correct with this new feature we never updated [the schema](src/index.ts). Will have a look at this next week.

**Comment by JJK801** [comment]
That what i assumed, i can make a PR if you want

**Comment by christopherafbjur** [comment]
@JJK801 Yes you're very welcome to do so 👍
