### ISSUE TITLE
Building Next.js app with nested Sanity Studio is broken by the plugin

### ISSUE THREAD

**Issue by JJK801** [christopherafbjur/sanity-plugin-icon-picker#50]
Hi,

i tried to build my next.js app using `next-sanity`, but when trying to access the studio, i've a client error related to this plugin (i'm investigating but can't figure where it come from).

removing the plugin make studio works.

![Capture d’écran 2023-06-16 à 12 40 45](https://github.com/christopherafbjur/sanity-plugin-icon-picker/assets/2821990/3aaf38b3-f2b7-467f-806a-83ce605b5f05)
![Capture d’écran 2023-06-16 à 12 40 21](https://github.com/christopherafbjur/sanity-plugin-icon-picker/assets/2821990/0e15a3ff-08e8-4e30-844a-7b150d28ff3d)

**Comment by christopherafbjur** [comment]
@JJK801 Is it possible for you to go with the solution explained in #33?

**Comment by JJK801** [comment]
> @JJK801 Is it possible for you to go with the solution explained in #33?

Yes of course, sorry for the duplicate
