### ISSUE TITLE
Error on production and built but not on development

### ISSUE THREAD

**Issue by julimancan** [christopherafbjur/sanity-plugin-icon-picker#58]
Hi I keep getting this error: Uncaught (in promise) ReferenceError: create$5 is not defined, I used the plugin for the simplest icon picker in an array. Installed the plugin and set it up in the plugins section of the sanity config object. And everything works on development mode but not after building. I have a nextjs site with the studio embedded into it, Maybe that has something to do with it.

**Comment by liamb13** [comment]
Hi @julimancan, this is mentioned in the https://github.com/christopherafbjur/sanity-plugin-icon-picker#faq.

To fix, update your next.config and add:
`swcMinify: false`
