### ISSUE TITLE
Support for font awesome 6

### ISSUE THREAD

**Issue by MikeCastillo1** [christopherafbjur/sanity-plugin-icon-picker#60]
Hello, 

This plugin is very helpfull, is there a way to add support for font awesome 6?, I notice that some icons are not there like Xmark.

I think you use react icons, I'm not sure where to add the library for font awesome 6.

Regards
Miguel Angel

**Comment by christopherafbjur** [comment]
Hi @MikeCastillo1 please refer to https://github.com/christopherafbjur/sanity-plugin-icon-picker#configurations which will allow you to setup your own configuration with this font awesome version that you describe
